USE [master]
GO

CREATE DATABASE [FIDO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FIDO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\FIDO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FIDO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\FIDO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FIDO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FIDO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FIDO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FIDO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FIDO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FIDO] SET ARITHABORT OFF 
GO

ALTER DATABASE [FIDO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FIDO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FIDO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FIDO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FIDO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FIDO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FIDO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FIDO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FIDO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FIDO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FIDO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FIDO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FIDO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FIDO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FIDO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FIDO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FIDO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FIDO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FIDO] SET  MULTI_USER 
GO

ALTER DATABASE [FIDO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FIDO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FIDO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FIDO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FIDO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FIDO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FIDO] SET  READ_WRITE 
GO


